<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>disable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <PackageId>Annoy.Net</PackageId>
    <Title>Annoy.NET</Title>
    <Version>1.1.0</Version>
    <Authors>trainhead</Authors>
    <Description>Cross-platform C# wrapper for Spotify Annoy.</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/TrainHead-software/annoy.net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TrainHead-software/annoy.net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>annoy;nearest-neighbor-search;unity</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>false</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\dev.trainhead.annoy.net\Runtime\Annoy.cs" Link="Annoy.cs" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Link="README.md" />
    <None Include="$(AnnoyNativeWindowsPath)" Pack="true" PackagePath="runtimes/win-x64/native/" Visible="false" Condition="'$(AnnoyNativeWindowsPath)' != '' and Exists('$(AnnoyNativeWindowsPath)')" />
    <None Include="$(AnnoyNativeLinuxPath)" Pack="true" PackagePath="runtimes/linux-x64/native/" Visible="false" Condition="'$(AnnoyNativeLinuxPath)' != '' and Exists('$(AnnoyNativeLinuxPath)')" />
    <None Include="$(AnnoyNativeMacPath)" Pack="true" PackagePath="runtimes/osx-x64/native/" Visible="false" Condition="'$(AnnoyNativeMacPath)' != '' and Exists('$(AnnoyNativeMacPath)')" />
  </ItemGroup>
</Project>
